Реализует задание module4-task3
htmlacademy-nodejs/468109-buy-and-sell-3 pull request #11
Opened 2021-06-15 18:25 UTC by VitalyIonov

2021-06-18 09:49 UTC, Krabaton requested changes

2021-06-18 09:49 UTC, Krabaton commented on src/express/middlewares/upload.js
> +const upload = multer({storage});
Стоп, а добавить ограничение на размер файла? Там же 

fileSize | For multipart forms, the max file size (in bytes) | Infinity
-- | -- | --




Я могу любой файл прислать, сервер же положить можно просто послав терабайтный файл.

2021-06-18 09:49 UTC, Krabaton commented on src/express/middlewares/upload.js
> +const upload = multer({storage});
Плюс файлы мы фильтруем или нет? По хорошему мы должны разрешать присылать только файлы с определённым расширением
```
function fileFilter (req, file, cb) {
 
  // The function should call `cb` with a boolean
  // to indicate if the file should be accepted
 
  // To reject this file pass `false`, like so:
  cb(null, false)
 
  // To accept the file pass `true`, like so:
  cb(null, true)
 
  // You can always pass an error if something goes wrong:
  cb(new Error('I don\'t have a clue!'))
 
}
```

2021-06-19 07:26 UTC, VitalyIonov commented on src/express/middlewares/upload.js
> +const upload = multer({storage});
исправлено

2021-06-19 08:02 UTC, merged