module2-task1
htmlacademy-nodejs/468109-buy-and-sell-3 pull request #3
Opened 2021-01-24 14:13 UTC by VitalyIonov

2021-01-24 14:20 UTC, LordotU requested changes

2021-01-24 14:20 UTC, LordotU commented on src/service/cli/generate.js
> +    console.error(chalk.red(`Can't write data to file...`));
Сообщения перепутаны местами. Ошибка должна быть в блоке `catch`

2021-01-27 09:04 UTC, VitalyIonov commented on src/service/cli/generate.js
> +    console.error(chalk.red(`Can't write data to file...`));
Да, да, я почти сразу поменял их местами в этом коммите - https://github.com/htmlacademy-nodejs/468109-buy-and-sell-3/pull/3/commits/f62c480e5e10967efec81868cba325b1023a2085

2021-01-27 10:33 UTC, LordotU approved these changes

2021-01-27 10:33 UTC, merged