module4-task1
htmlacademy-nodejs/468109-buy-and-sell-3 pull request #9
Opened 2021-03-03 14:35 UTC by VitalyIonov

2021-03-05 17:13 UTC, LordotU requested changes

2021-03-05 17:13 UTC, LordotU commented on src/service/middlewares/offerValidator.js
> +    res.status(HttpCode.BAD_REQUEST)
По-моему, в константах не определен `BAD_REQUEST`. Лишние зависимости - такое себе, но можно было бы заюзать https://www.npmjs.com/package/http-status-codes

2021-03-12 09:00 UTC, VitalyIonov commented on src/service/middlewares/offerValidator.js
> +    res.status(HttpCode.BAD_REQUEST)
Поправил. Согласен, в основном проекте заюзаю эту библиотеку

2021-03-13 17:41 UTC, dean992008 requested changes

2021-03-13 17:41 UTC, dean992008 commented on src/service/api/index.js
> +(async () => {
Здесь не корректно делать IIFE, так как при он будет срабатывать даже при запуске help и generate. 
Правильнее сделать функцию которая будет вызываться непосредственно.

Также тут проблема в том что роуты добавляются анихроно и при создании тестов будет проблема. 
Конкретно здесь правильнее прочитать данные синхронно 1 раз и закешировать результат в переменую которую возвразять при повторном обращении.

2021-03-13 17:41 UTC, dean992008 commented on src/utils.js
> +module.exports.checkTextMatch = (search, text) => {
Это не ошибка но рекомендация:
Лучше обьявлять все импортироуемые значения как локальные, после чего экспортировать значение в конце модуля. Например:
```
module.exports = {
  checkTextMatch,
  shuffle,
  getRandomInt
}
```

2021-03-13 17:41 UTC, dean992008 commented on src/service/middlewares/commentValidator.js
> +'use strict';
Фактически это дубль `offerValidator.js`, я бы предлижил сделать более универсальную функцию, которая будет принимать на вход массив полей и возвращять из него функции в которой будут доступны эти поля через замыкания.

2021-03-13 21:37 UTC, VitalyIonov commented on src/service/middlewares/commentValidator.js
> +'use strict';
Спасибо. Сделал так в личном проекте

2021-03-14 06:51 UTC, VitalyIonov commented on src/service/middlewares/commentValidator.js
> +'use strict';
Ну и в этом по итогу поправил, чтобы не было расхождений

2021-03-14 21:12 UTC, dean992008 commented on src/service/middlewares/commentValidator.js
> +'use strict';
Не вижу исправлений по этому коментарию. Проверь закомитил или возможно нет. 
Я прийму этот PR чтобы не блокировать работу, и если что отправишь в сделающем задании.

2021-03-14 21:12 UTC, merged

2021-03-14 21:21 UTC, dean992008 commented on src/service/middlewares/commentValidator.js
> +'use strict';
Увидел, ты сделал новый модуль, и оставил старые. Отрефактори, если еще не отрефкторил, и просто удали старие.